### ISSUE TITLE
Create a generate node.js script that creates a good loadtesting dataset.

### ISSUE THREAD

**Issue by dimitrydhondt** [dimitrydhondt/inner-gerbil#1]
Create a generate node.js script that creates a good loadtesting dataset.
See https://github.com/dimitrydhondt/elasjs/blob/master/generate.js for an example

**Comment by FrankDhondt** [comment]
Maybe we can use an existing package to generate certain data like http://chancejs.com/ or https://github.com/marak/Faker.js/

**Comment by dimitrydhondt** [comment]
I'll close this issue, as we discussed we would use the import procedure @renardeau is building, and allow it to import realistic data multiple times to generate a simulated set of groups. Bernard will add parameters to his import procedure to prefix the group name, and perhaps some more parameters to apply variation in the dataset (like shift all coördinates of parties by X latitiude and Y longitude), etc..
