### ISSUE TITLE
ESLint Gruntfile.js Jakefile.js 

### ISSUE THREAD

**Issue by dimitrydhondt** [dimitrydhondt/inner-gerbil#17]
They are not compliant with the eslint rules...

**Comment by FrankDhondt** [comment]
I'm getting errors like the one below when I run eslint, didn't @dimitrydhondt already fix this?
1:1  error    Rule 'no-empty-class' was removed and replaced by: no-empty-character-class no-empty-class

**Comment by FrankDhondt** [comment]
Will run eslint directly on file for now because running on project gives too many errors about deprecated rules.
