### ISSUE TITLE
OrderBy no longer works on parties

### ISSUE THREAD

**Issue by FrankDhondt** [dimitrydhondt/inner-gerbil#20]

**Comment by dimitrydhondt** [comment]
I've tested this : 

http://inner-gerbil-test.herokuapp.com/parties?orderBy=name

And that seems to work. Can you confirm ?

Dimi

**Comment by FrankDhondt** [comment]
Looks like the case-sensitivity changed, code in arty-gerbil used orderby which used to work. Will change arty-gerbil and close this issue.
