### ISSUE TITLE
Call from arty-gerbil no longer working after security is added

### ISSUE THREAD

**Issue by FrankDhondt** [dimitrydhondt/inner-gerbil#21]
![inner-gerbil issue 21](https://cloud.githubusercontent.com/assets/12109288/11087924/8185adb4-885e-11e5-9634-e17858fb1b4b.PNG)

**Comment by FrankDhondt** [comment]
![inner-gerbil issue 21](https://cloud.githubusercontent.com/assets/12109288/11087886/420e3be2-885e-11e5-9c71-ae9954442350.PNG)

**Comment by dimitrydhondt** [comment]
Added header to sri4node 1.1.24, checked in a package.json

run : 
npm install
npm upgrade

And try again..

**Comment by dimitrydhondt** [comment]
@FrankDhondt Can you confirm this is working ? I've also deployed to the test environment.

Dimi

**Comment by FrankDhondt** [comment]
If I add the change to my local sri4node 1.1.23 it works.

**Comment by FrankDhondt** [comment]
Waiting for upgrade of sri4node in inner-gerbil to close this issue

**Comment by dimitrydhondt** [comment]
We will in all likelihood remove CORS from sri4node. It is not up to sri4node to make policy decisions on things like CORS. Please prepare inner-gerbil, ok ?

**Comment by dimitrydhondt** [comment]
I'm moving the CORS code to inner-gerbil now.

**Comment by dimitrydhondt** [comment]
It should be working now. Can you try with latest sri4node ?

**Comment by FrankDhondt** [comment]
It's working now, closing issue.
