### ISSUE TITLE
'npm test' not running

### ISSUE THREAD

**Issue by dimitrydhondt** [dimitrydhondt/inner-gerbil#22]
I get : 
1) Sri4node testing Elas import testing Import users should load users from CSV file:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
  

  2) Sri4node testing Elas import testing Import messages should load messages from CSV file:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

Can you have a look @renardeau ?

**Comment by renardeau** [comment]
It looks like the PUT is not giving any response anymore. Not sure why that is yet, but it looks to be related to new version of sri4node: the problem disappears when rolling back to sri4node 1.1.23. 
@dimitrydhondt 
Any idea what has changed in version 1.1.24?

**Comment by dimitrydhondt** [comment]
Yes. I'll fix this.

**Comment by dimitrydhondt** [comment]
Still looking :)

**Comment by dimitrydhondt** [comment]
Found it. Wim had (correctly) pointed out that a create on a PUT MUST return 201 Created. This is in the HTTP spec. So we changed the SRI spec, and sri4node to reflect this. The code in the *import functions did not expect this, and resulted in parsing errors, but silently ignored the error (no .catch() at the end of the chain).
