### ISSUE TITLE
support for letscodes

### ISSUE THREAD

**Issue by eeemarv** [dimitrydhondt/inner-gerbil#24]
Letscodes (or better just 'codes' or 'accountcodes' as the system is not specific to lets) are not supported yet. I think they should be in the membership or 'partyrelations' as it is called in inner-gerbil.

**Comment by dimitrydhondt** [comment]
So we simply add 'code' to partyrelations ?
In any outcome of the discussion on what should be used to identify a person in the UI, we will need to support "letscode" for some groups. Personally I would prefer to ditch the codes altogether.

So I see a possible outcome in that discussion as : 

- We have an "alias" and a full name on the /parties/x
- We have "code" on /partyrelations/x

A setting in the admin module selects if people are shown with full name, code or alias.

I think it will be the only way to accomodate everyone's whishes.
