### ISSUE TITLE
Rename 'parties'?

### ISSUE THREAD

**Issue by eeemarv** [dimitrydhondt/inner-gerbil#25]
Parties is not really a name that does tell a lot. 
![party-1](https://cloud.githubusercontent.com/assets/3982071/11317597/e1362194-9033-11e5-9598-f45ac64bd32b.gif)
I propose to split parties into 'users' and 'groups'. That seems much more sensible to me. 
The api has to be logical to the outside world. It doesn't necessarily need to represent one on one the inner structure of the data store. Moreover, the inner structure of the data store might change over time or it could be that in the future there is a switch to another storage type (i.e a non-relational database). In other words, the organisation of the api is too tightly coupled to the inner structure of the data store. 
At the same time, more sensible naming is less documentation and better developer experience.

**Comment by dimitrydhondt** [comment]
We went over this a couple of times. We went back and forth between users+groups and parties. We landed with a general concept "party". The use of 'party' here refers to a legal party as used in law : 
https://en.wikipedia.org/wiki/Party_(law)

What do the others think ?

**Comment by FrankDhondt** [comment]
I would stick with "party", like Dimitry explains this what you would use
when describing legal contracts/transactions which lets transactions
essentially are.
Op 22-nov.-2015 11:37 schreef "dimitrydhondt" <notifications@github.com>:

**Comment by renardeau** [comment]
Discussed in hangout meeting (and in analysis phase):
Party offers the largest flexibility (and already on place). Kept as is.
