### ISSUE TITLE
Login with email

### ISSUE THREAD

**Issue by eeemarv** [dimitrydhondt/inner-gerbil#27]
In parties:
```javascript
    login: $s.string('Login for accessing the API. Only people have a login.', 3),
```
Just use the email address as a login? To prevent to maintain this extra field.

**Comment by dimitrydhondt** [comment]
I guess this is a functional question. Should we keep this in github ? Or close here, and maintain functional issues. Perhaps we should register a https://basecamp.com/ team ?

**Comment by dimitrydhondt** [comment]
For me this is fine, btw. I just think we need to consult the functional group on it.

**Comment by eeemarv** [comment]
In order not to scatter around all info (also with multiple logins etc) I would keep everything on Github and simply create a label 'functional' for it. The functional group can also be directed to Github and 
filter the issues with the 'functional' flag.

**Comment by eeemarv** [comment]
I was looking to create a 'functional' label here on Github, but I don't see the settings. I guess you, @dimitrydhondt is the only one who can create new labels. ref #26

**Comment by dimitrydhondt** [comment]
Nope, I cannot. Issue tracking in github is basic :-)

**Comment by dimitrydhondt** [comment]
Besides that I would currently focus on getting out a first functional release. And keep this discussion for after the demo of this release.

**Comment by dimitrydhondt** [comment]
The reason we wanted this is to allow people to be a member, even if they don't have an email address.

**Comment by eeemarv** [comment]
https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/

Yes, you can create new labels.

**Comment by dimitrydhondt** [comment]
Done ! Start tagging :-)

**Comment by renardeau** [comment]
Discussed in Hangout -> keep previous decision of functional group: login as separate field remains

**Comment by eeemarv** [comment]
Is it documented this was a decision of the functional group? 
All notifications and password resets go by email. And 2015 there are very few people who don't have an email address. For those few rare cases there can be found easily a solution. Admins can make email addresses for these people. There are the free providers like Google, Yahoo and Microsoft and if privacy is a concern then you can choose for example riseup.net or provide an email address under the url of the (lets)group.

**Comment by dimitrydhondt** [comment]
Well we don't have detailed notes of all of the functional meetings. And it is indeed a minority. But does it hurt to support login on top of e-mail address ? In any case it's a minor issue, no ?
