### ISSUE TITLE
Add support for profile images on parties

### ISSUE THREAD

**Issue by dimitrydhondt** [dimitrydhondt/inner-gerbil#29]

**Comment by dimitrydhondt** [comment]
In hangout meeting discussed : 

Inner gerbil should act as proxy to abstract actual data storage from client.
Storage in BLOB table or S3 service should be pluggable.

**Comment by eeemarv** [comment]
Better S3 otherwise this could become bottleneck. Take care to set up a IAM user with access only to S3 and delete the user with root access on AWS for safety. (In event keys are pushed by mistake to Github, always deleted the user and create a new one. Bots are scanning Github for credentials. Could be costly mistake of several 10000s euros)

**Comment by dimitrydhondt** [comment]
I will make this part pluggable, and only activate S3 for my local development + release to test (and later prod). For local development I will make sure images can be served from a local folder/table.

**Comment by dimitrydhondt** [comment]
Or I could create a special account for testing on S3 and share the credentials only via SMS to you guys ?

**Comment by dimitrydhondt** [comment]
Or I can add everyone's user in a group on S3 and provide access to the test environment bucket ?
In any case never include credentials in github, as Maarten stated before.

**Comment by dimitrydhondt** [comment]
I've been doing some investigation on handling the multipart/form-data in Node.js.

 * A resonable attempt for Express -> S3 streaming is here : 
http://thau.me/2014/02/nodejs-streaming-files-to-amazons3/

The main problem is that S3 requires Content-Length to be sent upfront (unless you use multipart on S3 as well but it seems to require at least 5MB of buffering in inner-gerbil - so that would not help much). 

It's is not possible to know the filesizes before receiving and parsing the full multipart/form-data.

So the best strategy in my opinion will be to put the files in temp files on the server first, and then send them to S3. At that point we have the file sizes, but we are not using memory (creating the temp files can be done in a streaming fashion).

We then need to take into account to *always* delete the temp files. Otherwise this is a potential denial-of-service vulnerability (out-of-disk situations could bring down the server). For the same reasons we need to put a limit on the size of the files & number of files in the multipart/form-data.

We need to register a middleware to parse the multipart/form-data. Multer looks like a good choice. It is built on top of busboy : https://www.npmjs.com/package/multer

For accessing S3 initmidate looks like a good choice : https://www.npmjs.com/package/intimidate 
Intimidate does retries with exponential backoff. This is always a must for accessing cloud-services.
In fact the UI's we build should also to retry with exponential backoff when talking to inner-gerbil. This solves intermittend network glitches + recycling behaviour of dyno's + redeploys, etc..

Still to investigate: does multer allows us to place filesize & count limits on the incoming data ?

**Comment by dimitrydhondt** [comment]
Multer passes setting about maximum form data / file size / file count into busboy, so that should take care of setting limits to the uploads:
https://www.npmjs.com/package/multer#limits

It does not clean any temp files created though. Luckily someone already wrote a reaper for multer : 

https://github.com/joelabair/multer-autoreap

So putting al of this together should provide a DoS safe implementation for storing files in S3...

**Comment by dimitrydhondt** [comment]
Current status : multer is responding well. File uploads are working. In order to integrate both multer and multer-autoreap I had to extend sri4node to support multiple middleware functions on custom routes. Tests show that the files are correctly being removed after handling the incoming request.

Next : Stream the files to S3 via intimidate !

**Comment by dimitrydhondt** [comment]
I'll create a group of users in S3. That group will gain access to the test bucket on S3. I'll add anyone who wants access to the bucket. I'll also add support for storing files in a blob table to simulate S3 to keep running the software convenient for local development. When the environment exposes S3 credentials I'll use S3, otherwise a local blob table.

**Comment by dimitrydhondt** [comment]
Intimidate seems a bit of a dead end. It only supports uploads. *sigh...* 
Other candidates : use the aws-sdk directly, or the higher-level node-s3-client... 

https://github.com/andrewrk/node-s3-client

**Comment by dimitrydhondt** [comment]
Upload & Download is working.

**Comment by dimitrydhondt** [comment]
I've extracted the handling of attachments into a reusable module : 

https://github.com/dimitrydhondt/sri4node-attachments

**Comment by eeemarv** [comment]
Have you looked at blue-imp-fileupload? It can do image resizing at client side.
https://www.npmjs.com/package/blueimp-file-upload

**Comment by dimitrydhondt** [comment]
The server-side is done. @eeemarv your suggestion has to do with arty-gerbil, right ? Closing this issue.
