### ISSUE TITLE
rename 'zipcode' ?

### ISSUE THREAD

**Issue by eeemarv** [dimitrydhondt/inner-gerbil#34]
The documentation says:
`zipcode: 4 digit postal code of the city for an address.`

Then name it `postalcode` directly?
Zipcode is USA-only (has at least 5 digits), the rest of the world uses postal codes.

**Comment by dimitrydhondt** [comment]
Ok. Sounds correct to me. Will change it.

**Comment by dimitrydhondt** [comment]
Working on it now.

**Comment by dimitrydhondt** [comment]
Done.
