### ISSUE TITLE
definition transaction: from/to parties / partyrelations

### ISSUE THREAD

**Issue by eeemarv** [dimitrydhondt/inner-gerbil#35]
A transaction is now defined from party to party. 

I think this is wrong. It should be from partyrelation to partyrelation

The partyrelations are the memberships and accounts. 
You don't submit a transaction to persons/organisations themselves. You do a transaction to their accounts.

ref #28

**Comment by dimitrydhondt** [comment]
In any case the details are in /partyrelations.
What do the others think ? Is it sensible to also store the /partyrelations i.o. the /parties in /transactions ?

@sorokh @FrankDhondt @renardeau

**Comment by eeemarv** [comment]
@dimitrydhondt 
>In any case the details are in /partyrelations.

You meant /transactionrelations?

**Comment by dimitrydhondt** [comment]
Ah yes, /transactionrelations :)

**Comment by dimitrydhondt** [comment]
I'm assuming this is OK. No further discussion was done. And there is no distinction in the total amount of information / detail. Closing issue.
