### ISSUE TITLE
Integrate a standard logging library

### ISSUE THREAD

**Issue by dimitrydhondt** [dimitrydhondt/inner-gerbil#36]
Instead of using adhoc logging, we should use a standard library.
The most commonly used one is winston : 

https://github.com/winstonjs/winston

I read the docs and it seems to offer everything than we will likely need.
Because it has a very large user base plugins for online logging services are also available.
For example to log to LogEntries.com : 

https://www.npmjs.com/package/winston-logentries

or Loggly.com

https://github.com/winstonjs/winston-loggly

etc..

What do you guys think ? Will this cover our needs ?
Do we agree to pick this one ?

**Comment by dimitrydhondt** [comment]
I've been trying out winston on sri4node-attachements : 

https://github.com/dimitrydhondt/sri4node-attachments

This new project isolates the attachment handling into a reusable module. It allows you to support attachments on a set of sri4node resources of choice.
It works with local filesystem and S3. In the future I will add a BLOB database table as storage.

**Comment by dimitrydhondtvsko** [comment]
It turns out Winston does not run in the browser, so only server-side... I prefereert solutions that run client- and server-side..

https://github.com/winstonjs/winston/issues/287

**Comment by dimitrydhondtvsko** [comment]
Bunyan, the seconden contendervdoes have a Nice port to run in the browser : Browser Bunyan

http://philmander.com/client-side-logging-with-browser-bunyan.html

**Comment by dimitrydhondt** [comment]
Bunyan als documents it's native support for browserify : http://philmander.com/client-side-logging-with-browser-bunyan.html

**Comment by dimitrydhondt** [comment]
Wrong link... https://github.com/trentm/node-bunyan/blob/master/README.md#browserify

**Comment by dimitrydhondt** [comment]
At VSKO we are thinking about the following: instead of making everyone use a certain logging framework, why not simply overwrite console.info, console.warn and console.error (they exist both in node and in the browser) and use these.

We would use the log-levels in a sensible manner : ​

*info*​ is just general information that tells what the application is doing, be modest with this. ​

*warn*​ is something that didn't go as expected, but doesn't cause the software or the user any problem (for example a request failed, but after a retry it worked, it might be a problem somewhere else ). 

​*error*​ is if something really went wrong. For example saving a resource failed because of invalid schema, (and the user wasn't able to do what he wanted).

What do you think of this idea ? Does it make sense for *-gerbil as well ?
If you think this is a bad idea, don't hesitate to let le know why ;-)

**Comment by renardeau** [comment]
Sounds simple and easy to use as there would be no need to learn any new logging framework.
But then, what would we overwrite those methods with? Is this just a way to hide the logging framework used?
My requirements for the logging framework:
* easy to use
* allows to efficiently retrieve related logs (based on some request or thread id)

**Comment by dimitrydhondt** [comment]
Well the idea is that the standard console functions form an interface that we can implement with a logging framework, or a client library for a logging service, or a custom logging implemenentation, of simply not override the functions and use basic console logging, etc..

Personally I think logging to a logging service like LogEntries or Loggly via their client lib would be prefereable.

But in any case we would not be binding us to any fixed choice.

Plus : any existing library that we use will likely log to console as well, or use a logging framework that can be configured to log to console. So hopefully that would allow us to have all logs in 1 place. Although logging of sub-libraries is usually not something I want to see (besides ocasionally in development)

Well that's the idea. We haven't tried this in practice yet :-)

**Comment by dimitrydhondt** [comment]
I will proceed with this strategy, and see where it leads :-) Unless I get feedback from anyone else.
One detail : 

console.debug does not exist on Node.js (it does in the browser console object). Therefor I will log debug statements to console.log IF the process environment variable LOG_DEBUG is set.

That way we stick to the common denominator between client and server javascript. Yet we extract the verbose flag out of the code base. It has been an ugly thorn for some time now ;-)

**Comment by dimitrydhondt** [comment]
I suggest we add extra information to the logging behind the scenes (in the overwritten console.x functions to add log level, timestamp, request id, etc..)

For the request ID we still need to come up with a strategy. 

My basic thinking is that on the AngularJS side we need to elaborate on the sri-client library, and add a request ID in a custom HTTP header (automatically). On the server sri4node should then also log the incomming request ID whenever the server logs something (again in the overwritten console.x functions). And when we use sri-client on the server (it is the intention to make it work with both $http from AngularJS as well as needle + needle-retry on the Node.js / server side) the existing request ID should be forwarded automatically. This way, when we combine the logs of the front-end, back-end and 2nd-level back-end calls (etc..) we will be able to view the handling of a full request in one place. 

When logging to a service such as LogEntries/Loggly it is perhaps best to send a JSON object. These services are typically good at parsing JSON and allowing you to filter on the individual properties. Again this can be handled behind the scenes.

**Comment by dimitrydhondt** [comment]
Working on moving all logging into common.js -> debug/info/warn/error
Passing around of "logverbose" is being removed. As stated this becomes $LOG_DEBUG=TRUE

**Comment by dimitrydhondt** [comment]
By moving it into an environment variable we don't need to change the source code to activate debug logging.

**Comment by dimitrydhondt** [comment]
Done.
