### ISSUE TITLE
event history

### ISSUE THREAD

**Issue by eeemarv** [dimitrydhondt/inner-gerbil#37]
A big lack I've come to realise in eLAS, eLAND and inner-gerbil is there's not any history of the events that led to the current state of the data (apart from the transactions). 
Here's some read on event sourcing: https://github.com/meteor-space/event-sourcing.
So the suggestion is to store all events and use this as the primary source of data and build the current state from there. Events are only appended, never updated or deleted. Data gets lost on updates and deletes. So this won't be the case anymore.
Practically, the new jsonb type from Postgres 9.4 seems very suited to store events. 
This suggestion might come a bit late into the project I realise.

**Comment by dimitrydhondt** [comment]
We do have a standard audit & broadcast API : 

https://github.com/jgovaerts/sri-audit-broadcast

It serves 2 purposes : 

- Provide a full audit trail of any changes to resources on an SRI interface. 
- Provide a broadcast mechanism to allow clients to get notifications when resources change.

It should be possible to integrate this into inner-gerbil. In fact, come to think of it, the sri-audit-broadcast should have a standard sri4node integration. I'll book a ticket there. Then it would simply be a matter of installing the correct after* functions on inner-gerbil to get tracking & broadcasting on the API.

One hickup, however, is that it currently assumes our standard security API. This could be made more modular. The security API is not yet open sourced, but it will be in the weeks to come : 
https://github.com/rodrigouroz/sri-security-app

**Comment by dimitrydhondt** [comment]
https://github.com/jgovaerts/sri-audit-broadcast/issues/1

**Comment by dimitrydhondt** [comment]
@eeemarv Is this strategy acceptable to you ? I.e. : The problem of providing a full event stream is moved out of the code of inner-gerbil, and handled by a separate service. The integration with inner-gerbil would be a couple of lines of code to issue a PUT operation to the external service, whenever a PUT/DELETE was processed correctly.

Can I close this issue ?

**Comment by eeemarv** [comment]
Ok.
