### ISSUE TITLE
Add member images to testdata

### ISSUE THREAD

**Issue by FrankDhondt** [dimitrydhondt/inner-gerbil#40]
For easy integration of member image in arty gerbil we need some testdata

**Comment by dimitrydhondt** [comment]
Add a script to upload some dummu images after inserting via SQL.

**Comment by dimitrydhondt** [comment]
Frank,

Can you take this up with the upload implementation for a profile ?
I.e. Implement the upload, see that you can store a profile image, and then see that it is shown correctly for a member ?

A lot of members will not have a profile image, so a default should be used like first letter of firstname + first letter of lastname ? So mine would be DD, and yours would be FD.

Like in Google ?

Dimi

**Comment by dimitrydhondt** [comment]
I'll try to add one or two images in inner gerbil.

**Comment by dimitrydhondt** [comment]
I think adding them in the ./release-test.sh script with CURL would be the way to go.

**Comment by dimitrydhondt** [comment]
I'm trying to put an image : 

curl -X PUT -u annadv:test -filedata=@test/orange-boy-icon.png  https://inner-gerbil-test.herokuapp.com/parties/5df52f9f-e51f-4942-a810-1496c51e64db/profile.png

Somehow this gives me 500 internal error..

Investigating...

**Comment by dimitrydhondt** [comment]
Found it : 

curl -X PUT -u annadv:test -F 'filedata=@/home/ubuntu/workspace/inner-gerbil/test/orange-boy-icon.png' https://inner-gerbil-test.herokuapp.com/parties/5df52f9f-e51f-4942-a810-1496c51e6file.png

**Comment by dimitrydhondt** [comment]
Anna now has a profile image.

**Comment by dimitrydhondt** [comment]
The profile image is available at /parties/{guid}/profile.png
Use the same URL when putting. (profile.png)
