### ISSUE TITLE
Call to forPartiesReachableFromParties on contactdetails does not return data on inner-gerbil-test

### ISSUE THREAD

**Issue by FrankDhondt** [dimitrydhondt/inner-gerbil#41]
http://inner-gerbil-test.herokuapp.com/contactdetails?forPartiesReachableFromParties==5df52f9f-e51f-4942-a810-1496c51e64db

**Comment by dimitrydhondt** [comment]
Should be : http://inner-gerbil-test.herokuapp.com/contactdetails?forPartiesReachableFromParties=/parties/5df52f9f-e51f-4942-a810-1496c51e64db
