### ISSUE TITLE
Solving JSLint errors

### ISSUE THREAD

**Issue by renardeau** [dimitrydhondt/inner-gerbil#6]
In Brackets, lots of JSLint errors are reported. I started fixing the easiest ones on js/parties, others to follow

**Comment by dimitrydhondt** [comment]
I'm in doubt which of the linting tools for Javascript that we should use.. JSHint is said to be more pragmatic, more friendly. ESLint is another alternative. The little experience I have with JSLint is indeed that it is overly opinionated, and not very pragmatic..

Any advice on this ?

**Comment by renardeau** [comment]
To me, which linting tool doesn't matter much: any is better than none :-)
I picked JSLint because it is the one described in 'Javascript, the good parts'.
I'm new to javascript, so I still welcome any opinionated view ;-)
From what I can read, JSLint attaches more importance to style, where ESLint claims to be "Agenda Free" and wants the developer to be able to defines its own set of rules (http://eslint.org/docs/about/). 

Whichever we pick, it would be nice if it can be integrated in Brackets and if rationale behind reported errors/hints is well documented. For JSLint, JHLint and ESLint I found this https://jslinterrors.com website very useful to understand the risks of reported errors. It can also help to get an idea of the differences in rules between the three

**Comment by dimitrydhondt** [comment]
I've found this comparison : http://www.sitepoint.com/comparison-javascript-linting-tools/

I think ESLint seems to be the most user friendly (concise, yet readable output) and most modern of the four options..

A brackets integration for ESLint is also available via brackets-npm-registert : https://github.com/zaggino/brackets-npm-registry

It uses the standard ~/.eslintrc file

You can disable the jslint as described here :
 
http://stackoverflow.com/questions/27584301/adobe-brackets-disable-jslint-but-allow-jshint

I used the default .eslintrc from eslint-brackets : 

https://github.com/zaggino/brackets-eslint/blob/master/.eslintrc

Dimi

**Comment by dimitrydhondt** [comment]
Also an interesting read : http://rangle.io/blog/understanding-the-real-advantages-of-using-eslint/

**Comment by renardeau** [comment]
Switched to ESLint and applied corrections to (most) reported errors
